// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DialToolsForVS
{
    static class Vsix
    {
        public const string Id = "d4ce1d82-9bf6-4136-bd56-43cde615e0db";
        public const string Name = "Surface Dial Tools for Visual Studio";
        public const string Description = @"Adds features to Visual Studio specific to the Surface Dial. You don't need a Surface Book or Surface Studio to take advantage of the Surface Dial.";
        public const string Language = "en-US";
        public const string Version = "0.8";
        public const string Author = "Mads Kristensen";
        public const string Tags = "surface, dial";
    }
}
